# Generated by Django 5.2.7 on 2025-10-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=20),
        ),
    ]
