# Generated by Django 5.2.7 on 2025-10-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_featured_drug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(default='null', verbose_name='name'),
            preserve_default=False,
        ),
    ]
