# Generated by Django 5.2.7 on 2025-10-19 04:59

import drugs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='image',
        ),
        migrations.AddField(
            model_name='drug',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=drugs.models.upload_thumbnail),
        ),
        migrations.AlterField(
            model_name='drug',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
