# Generated by Django 5.2.7 on 2025-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_remove_drug_image_drug_thumbnail_alter_drug_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='keywords',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
